name: innopolis_test
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_lints: ^1.0.4
  dio: ^4.0.1
  fluttertoast: ^8.0.8

# flutter packages pub run build_runner build --delete-conflicting-outputs
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^9.1.3
  build_runner: ^2.1.4
  json_serializable: ^6.7.1
  json_annotation: ^4.1.0
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1



flutter:
  uses-material-design: true
